# Generated by Django 4.0.6 on 2024-06-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_userchat_room_description_room_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
